import { z } from 'zod'
import type { BarId } from './primitives'

// The effect catalog: everything that can happen in the world. The LLM picks an id and a
// target; every number below belongs to the code. The LLM never sees or produces them.
// The player does see them: the cards show exactly what a decision will do.

export const EFFECT_IDS = [
  // player decisions
  'tax_cut',
  'fiscal_stimulus',
  'austerity',
  'regional_investment',
  'anti_corruption_drive',
  'press_crackdown',
  'eu_accession_bid',
  'eu_membership',
  'trade_agreement',
  'sanctions',
  'diplomatic_protest',
  'military_aid',
  'military_buildup',
  // what other countries do
  'energy_cutoff',
  'foreign_investment',
  'eu_process_frozen',
  'eu_funds',
  // what society and the world do (mostly delayed consequences, i.e. fired seeds)
  'protest_wave',
  'inflation_spike',
  'budget_gap',
  'elite_backlash',
  'nationalist_backlash',
  'investor_confidence',
  'regional_boom',
  'regional_tension',
  // Faz 2
  'interest_rate_hike',
  'minimum_wage_raise',
  'privatization',
  'tourism_campaign',
  'mega_project',
  'social_housing',
  'tariff_hike',
  'energy_deal',
  'security_operation',
  'judicial_reform',
  'cabinet_reshuffle',
  'emergency_rule',
  'national_rally',
  'opposition_crackdown',
  'education_reform',
  'migration_control',
  'state_visit',
  'backchannel_talks',
  'peace_mediation',
  'recall_ambassador',
  'defense_pact',
  'humanitarian_aid',
  'arms_embargo',
  'summit_hosting',
  'border_deployment',
  'military_exercise',
  'cross_border_operation',
  'arms_purchase',
  'defense_industry',
  'mobilization',
  'naval_show_of_force',
  'ceasefire_offer',
  'reckless_gambit',
  'border_incident',
  'cyber_attack',
  'tourism_boycott',
  'refugee_wave',
  'security_crisis',
  'diplomatic_support',
  'credit_downgrade',
  'credit_upgrade',
  'energy_discount',
  'military_threat',
  'scandal',
  'strike_wave',
  'public_goodwill',
  'export_boom'
] as const
export const EffectId = z.enum(EFFECT_IDS)
export type EffectId = z.infer<typeof EffectId>

/** Who may cause an effect: the player's government, another country, or society/the world itself. */
export type ActorKind = 'player' | 'foreign' | 'world'

export type EffectCategory = 'economy' | 'domestic' | 'foreign' | 'military' | 'world'

export const CATEGORY_LABELS: Record<EffectCategory, string> = {
  economy: 'Ekonomi',
  domestic: 'İç siyaset',
  foreign: 'Dış politika',
  military: 'Askerî',
  world: 'Dünya'
}

export interface Modifier {
  /** Which country the change lands on: the target, the acting country, or the owner of a target province. */
  on: 'target' | 'actor' | 'owner'
  bar: BarId
  delta: number
  /** 'once' hits when the effect starts; 'per_turn' repeats every turn while active. */
  mode: 'once' | 'per_turn'
}

export type EffectRule =
  | { kind: 'target_is_actor' }
  | { kind: 'target_not_actor' }
  | { kind: 'province_owned_by_actor' }
  | { kind: 'requires_active'; effectId: EffectId; on: 'actor' | 'target' }
  | { kind: 'forbids_active'; effectId: EffectId; on: 'actor' | 'target' }
  /** The acting country may have at most this many copies running at once. */
  | { kind: 'max_active'; count: number }
  /** The acting country's military must exceed the target's by this much. */
  | { kind: 'military_edge'; margin: number }

export interface EffectDef {
  id: EffectId
  /** Turkish name shown in the game. */
  label: string
  /** One Turkish line for the decision card: what it is, and its catch. */
  summary: string
  /** What it represents, in words, for the LLM. Deliberately contains no numbers. */
  hint: string
  category: EffectCategory
  target: 'country' | 'province'
  actors: readonly ActorKind[]
  /** Political capital the player spends. Others don't pay. */
  cost: number
  /** How many turns it stays active; null = until removed. */
  durationTurns: number | null
  /** At most one active copy per (actor, target). Consequences are not unique: they stack. */
  unique: boolean
  rules: readonly EffectRule[]
  modifiers: readonly Modifier[]
  tags: readonly string[]
  /** False for player moves that are not offered as a card (e.g. a failed attempt the AI records). */
  card?: boolean
}

const DOMESTIC = [{ kind: 'target_is_actor' }] as const satisfies readonly EffectRule[]
const BILATERAL = [{ kind: 'target_not_actor' }] as const satisfies readonly EffectRule[]

const once = (bar: BarId, delta: number, on: Modifier['on'] = 'target'): Modifier => ({ on, bar, delta, mode: 'once' })
const perTurn = (bar: BarId, delta: number, on: Modifier['on'] = 'target'): Modifier => ({ on, bar, delta, mode: 'per_turn' })

export const EFFECTS: { readonly [K in EffectId]: EffectDef & { id: K } } = {
  tax_cut: {
    id: 'tax_cut',
    label: 'Vergi indirimi',
    summary: 'Halk hemen sevinir, cepler rahatlar. Kasa zayıflar; bütçe bunun hesabını ileride sorabilir.',
    hint: 'Lower taxes: an immediate popularity boost and more money in pockets, at a fiscal cost now and later.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('approval', 5), perTurn('welfare', 1), perTurn('economy', -1)],
    tags: ['ekonomi', 'vergi']
  },
  fiscal_stimulus: {
    id: 'fiscal_stimulus',
    label: 'Mali teşvik paketi',
    summary: 'Ekonomiyi hızla büyütür, piyasalar kaşlarını kaldırır. Para basmanın bedeli enflasyon olarak dönebilir.',
    hint: 'Government spending push: fast growth now, inflation risk later.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: [...DOMESTIC, { kind: 'forbids_active', effectId: 'austerity', on: 'target' }],
    modifiers: [perTurn('economy', 2), once('approval', 1), once('reputation', -1)],
    tags: ['ekonomi', 'tesvik']
  },
  austerity: {
    id: 'austerity',
    label: 'Kemer sıkma',
    summary: 'Halk sıkıntı çeker, onay düşer. Ekonomi yavaş toparlanır, piyasalar bunu ödüllendirebilir.',
    hint: 'Spending cuts: painful and unpopular now, slowly repairs the economy, may win investor trust.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 5,
    unique: true,
    rules: [...DOMESTIC, { kind: 'forbids_active', effectId: 'fiscal_stimulus', on: 'target' }],
    modifiers: [once('approval', -4), perTurn('welfare', -2), perTurn('economy', 2)],
    tags: ['ekonomi', 'kemer-sikma']
  },
  regional_investment: {
    id: 'regional_investment',
    label: 'Bölgesel yatırım',
    summary: 'Bir ilinde altyapı ve iş. Kasadan çıkarken refahı artırır; meyvesini ileride verebilir. Aynı anda tek il.',
    hint: 'Infrastructure and jobs programme in one of your own provinces.',
    category: 'economy',
    target: 'province',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: [{ kind: 'province_owned_by_actor' }, { kind: 'max_active', count: 1 }],
    modifiers: [perTurn('economy', -1, 'owner'), perTurn('welfare', 1, 'owner'), once('approval', 1, 'owner')],
    tags: ['ekonomi', 'bolgesel']
  },
  anti_corruption_drive: {
    id: 'anti_corruption_drive',
    label: 'Yolsuzlukla mücadele',
    summary: 'Halk alkışlar, ekonomi rahatlar ama düzen sarsılır. Koltuklarını kaybedenler sessiz kalmayabilir.',
    hint: 'Investigations and purges of corrupt officials: popular, unsettles the establishment.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 5,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('approval', 4), once('stability', -3), perTurn('economy', 1)],
    tags: ['ic-siyaset', 'yolsuzluk']
  },
  press_crackdown: {
    id: 'press_crackdown',
    label: 'Basına baskı',
    summary: 'Kısa vadede sükûnet. Halk küser, dışarıda itibar kaybı; biriken öfke bir gün patlayabilir.',
    hint: 'Censorship and pressure on media: short-term calm, long-term resentment and bad press abroad.',
    category: 'domestic',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('stability', 4), once('approval', -1), once('reputation', -4), perTurn('welfare', -1)],
    tags: ['ic-siyaset', 'sansur']
  },
  eu_accession_bid: {
    id: 'eu_accession_bid',
    label: 'AB üyelik başvurusu',
    summary: 'Dünyada itibar kazandırır. Üyeliğe giden uzun yol; bazı başkentler buna sıcak bakmaz.',
    hint: 'Formally applying to join the European Union. A first step; membership itself comes later.',
    category: 'foreign',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: null,
    unique: true,
    rules: [...DOMESTIC, { kind: 'forbids_active', effectId: 'eu_membership', on: 'target' }],
    modifiers: [once('reputation', 3), once('sovereignty', -2), once('approval', 1)],
    tags: ['ab', 'diplomasi']
  },
  eu_membership: {
    id: 'eu_membership',
    label: 'AB üyeliği',
    summary: 'Ekonomi kalıcı olarak güçlenir, egemenlik belirgin biçimde azalır. Önce başvuru gerekir.',
    hint: 'Joining the European Union: trade and investment rise, sovereignty shrinks. Needs an accession bid first.',
    category: 'foreign',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: null,
    unique: true,
    rules: [
      ...DOMESTIC,
      { kind: 'requires_active', effectId: 'eu_accession_bid', on: 'target' },
      { kind: 'forbids_active', effectId: 'eu_process_frozen', on: 'target' }
    ],
    modifiers: [perTurn('economy', 1), once('sovereignty', -8), once('reputation', 5), once('approval', -2)],
    tags: ['ab', 'diplomasi', 'ekonomi']
  },
  trade_agreement: {
    id: 'trade_agreement',
    label: 'Ticaret anlaşması',
    summary: 'İki ekonomi birlikte büyür, ucuz ithalat yerli üreticiyi kızdırır. Aynı anda en fazla 2 anlaşma.',
    hint: 'Bilateral trade deal: both economies benefit for a while; domestic producers grumble.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 5,
    unique: true,
    rules: [...BILATERAL, { kind: 'max_active', count: 2 }],
    modifiers: [perTurn('economy', 1, 'actor'), once('approval', -1, 'actor'), perTurn('economy', 1)],
    tags: ['ticaret', 'diplomasi']
  },
  sanctions: {
    id: 'sanctions',
    label: 'Yaptırım',
    summary: 'Hedef ülkeyi sarsar, içeride milliyetçi destek getirir. Kendi ekonomin de zarar görür; karşılık gelebilir.',
    hint: 'Economic sanctions against another country: hurts the target more than the sender, invites retaliation.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 5,
    unique: true,
    rules: [...BILATERAL, { kind: 'max_active', count: 2 }],
    modifiers: [perTurn('economy', -2), once('reputation', -1), perTurn('economy', -1, 'actor'), once('approval', 2, 'actor')],
    tags: ['yaptirim', 'diplomasi']
  },
  diplomatic_protest: {
    id: 'diplomatic_protest',
    label: 'Diplomatik nota',
    summary: 'Resmî itiraz. Sembolik; sana puan kazandırmaz, karşı tarafın itibarını biraz zedeler. Bedava.',
    hint: 'A formal protest note: symbolic, small reputational cost for the target.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 0,
    durationTurns: 1,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('reputation', -1)],
    tags: ['diplomasi']
  },
  military_aid: {
    id: 'military_aid',
    label: 'Askerî yardım',
    summary: 'Başka bir ülkeye silah ve eğitim. Kendi gücünden verirsin; dostluk ileride karşılık bulabilir.',
    hint: 'Weapons and training sent to another country; may be repaid with friendship later.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 1,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('military', 3), once('military', -2, 'actor'), once('reputation', 1, 'actor')],
    tags: ['askeri', 'diplomasi']
  },
  military_buildup: {
    id: 'military_buildup',
    label: 'Askerî yığınak',
    summary: 'Ordu güçlenir, içeride güven artar. Pahalıdır; komşular bundan tedirgin olur.',
    hint: 'Mobilisation and procurement: stronger armed forces, costly, worries neighbours.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [perTurn('military', 2), perTurn('economy', -1), once('stability', 2), once('reputation', -2)],
    tags: ['askeri']
  },

  energy_cutoff: {
    id: 'energy_cutoff',
    label: 'Enerji kesintisi',
    summary: 'Tedarikçi ülke gaz veya petrol akışını kesiyor.',
    hint: 'A supplier country cuts gas or oil deliveries to the target.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 4,
    unique: true,
    rules: BILATERAL,
    modifiers: [perTurn('economy', -2), perTurn('welfare', -1), once('stability', -2)],
    tags: ['enerji', 'ekonomi']
  },
  foreign_investment: {
    id: 'foreign_investment',
    label: 'Yabancı yatırım dalgası',
    summary: 'Başka bir ülkenin şirketleri yatırım yapıyor.',
    hint: 'Companies from the acting country pour investment into the target.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 4,
    unique: true,
    rules: BILATERAL,
    modifiers: [perTurn('economy', 1), once('approval', 1)],
    tags: ['ekonomi', 'yatirim']
  },
  eu_process_frozen: {
    id: 'eu_process_frozen',
    label: 'AB süreci donduruldu',
    summary: 'Bir AB başkenti üyelik sürecini veto tehdidiyle durdurdu.',
    hint: 'An EU capital blocks the target’s accession process for a while.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 6,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('reputation', -3), once('approval', -3)],
    tags: ['ab', 'diplomasi']
  },
  eu_funds: {
    id: 'eu_funds',
    label: 'AB fonları',
    summary: 'Üyelikle gelen uyum fonları akmaya başladı.',
    hint: 'EU structural funds start flowing to a new member.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 5,
    unique: true,
    rules: BILATERAL,
    modifiers: [perTurn('economy', 1), perTurn('welfare', 1)],
    tags: ['ab', 'ekonomi']
  },
  protest_wave: {
    id: 'protest_wave',
    label: 'Protesto dalgası',
    summary: 'Biriken öfke sokaklara taşıyor.',
    hint: 'Mass street protests erupt against the government.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 2,
    unique: false,
    rules: [],
    modifiers: [once('stability', -7), once('approval', -4), perTurn('economy', -1)],
    tags: ['ic-siyaset', 'protesto']
  },
  inflation_spike: {
    id: 'inflation_spike',
    label: 'Enflasyon sıçraması',
    summary: 'Fiyatlar hızla yükseliyor, maaşlar eriyor.',
    hint: 'Prices surge and wages lose value.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 3,
    unique: false,
    rules: [],
    modifiers: [perTurn('economy', -1), perTurn('welfare', -2), once('approval', -3)],
    tags: ['ekonomi', 'enflasyon']
  },
  budget_gap: {
    id: 'budget_gap',
    label: 'Bütçe açığı',
    summary: 'Kasada delik açıldı, harcamalar kısılıyor.',
    hint: 'A widening budget deficit forces cuts.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 3,
    unique: false,
    rules: [],
    modifiers: [perTurn('economy', -2), once('welfare', -1), once('approval', -1)],
    tags: ['ekonomi', 'butce']
  },
  elite_backlash: {
    id: 'elite_backlash',
    label: 'Eski düzenin tepkisi',
    summary: 'Koltuğunu kaybedenler karşı hamleye geçiyor.',
    hint: 'Displaced power brokers strike back through courts, media and business.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 1,
    unique: false,
    rules: [],
    modifiers: [once('stability', -4), once('approval', -2)],
    tags: ['ic-siyaset']
  },
  nationalist_backlash: {
    id: 'nationalist_backlash',
    label: 'Milliyetçi tepki',
    summary: 'Egemenlik kaybına öfkelenen kesimler ayağa kalkıyor.',
    hint: 'Nationalists rally against lost sovereignty.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 1,
    unique: false,
    rules: [],
    modifiers: [once('approval', -4), once('stability', -2)],
    tags: ['ic-siyaset', 'milliyetcilik']
  },
  investor_confidence: {
    id: 'investor_confidence',
    label: 'Yatırımcı güveni',
    summary: 'Piyasalar disiplini ödüllendiriyor, sermaye geri dönüyor.',
    hint: 'Markets reward fiscal discipline; capital flows back in.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 3,
    unique: true,
    rules: [],
    modifiers: [perTurn('economy', 2), once('approval', 2)],
    tags: ['ekonomi', 'yatirim']
  },
  regional_boom: {
    id: 'regional_boom',
    label: 'Bölgesel kalkınma',
    summary: 'Yatırım yapılan bölge meyvesini veriyor.',
    hint: 'An invested region takes off, lifting living standards.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 3,
    unique: true,
    rules: [],
    modifiers: [perTurn('welfare', 1), once('approval', 2)],
    tags: ['ekonomi', 'bolgesel']
  },
  regional_tension: {
    id: 'regional_tension',
    label: 'Bölgesel gerginlik',
    summary: 'Komşular silahlanıyor, sınırda gerilim tırmanıyor.',
    hint: 'Neighbours arm up in response; tension rises on the border.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 2,
    unique: false,
    rules: [],
    modifiers: [once('stability', -3), perTurn('economy', -1), once('reputation', -2)],
    tags: ['askeri', 'gerginlik']
  },
  // ── Faz 2: the wider set, so free-text orders have somewhere to land ─────────
  // economy
  interest_rate_hike: {
    id: 'interest_rate_hike',
    label: 'Faiz artırımı',
    summary: 'Piyasalara disiplin mesajı verir, dışarıda güven kazandırır. Kredi pahalanır, büyüme yavaşlar, halk söylenir.',
    hint: 'Central bank raises interest rates: tames prices and wins market trust, slows growth and annoys borrowers.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: DOMESTIC,
    modifiers: [perTurn('economy', -1), once('reputation', 2), once('approval', -2)],
    tags: ['ekonomi', 'faiz']
  },
  minimum_wage_raise: {
    id: 'minimum_wage_raise',
    label: 'Asgari ücret zammı',
    summary: 'Çalışanın cebi rahatlar, sokak sevinir. İşverenin yükü ve enflasyon baskısı artar.',
    hint: 'Raise the minimum wage: popular and lifts living standards, costs employers and the economy.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('approval', 3), perTurn('welfare', 1), perTurn('economy', -1)],
    tags: ['ekonomi', 'ucret']
  },
  privatization: {
    id: 'privatization',
    label: 'Özelleştirme',
    summary: 'Kasaya bir anda para girer. Kamu malı satılınca halk tepki gösterir, stratejik varlıklar yabancıya geçebilir.',
    hint: 'Sell state-owned companies: a quick cash boost for the economy, unpopular, gives up some control.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 6,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('economy', 3), once('approval', -2), once('sovereignty', -2)],
    tags: ['ekonomi', 'ozellestirme']
  },
  tourism_campaign: {
    id: 'tourism_campaign',
    label: 'Turizm atağı',
    summary: 'Tanıtım ve teşviklerle turist çekilir. Önce harcama yapılır, gelir sonra gelir.',
    hint: 'Promote tourism abroad: an upfront cost, then steady income and a better image.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('economy', -1), perTurn('economy', 1), once('reputation', 1)],
    tags: ['ekonomi', 'turizm']
  },
  mega_project: {
    id: 'mega_project',
    label: 'Mega proje',
    summary: 'Köprü, havalimanı, kanal: halk gurur duyar, istikrar hissi artar. Borç yükü aylarca ekonomiye biner.',
    hint: 'A flagship infrastructure project: national pride now, heavy debt for months.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('approval', 3), once('stability', 1), perTurn('economy', -1)],
    tags: ['ekonomi', 'altyapi']
  },
  social_housing: {
    id: 'social_housing',
    label: 'Sosyal konut',
    summary: 'Dar gelirliye ev: refah uzun süre artar. İnşaat bütçesi ekonomiyi zorlar.',
    hint: 'Build social housing: slowly raises living standards, costs the budget.',
    category: 'economy',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 5,
    unique: true,
    rules: DOMESTIC,
    modifiers: [perTurn('welfare', 1), perTurn('economy', -1), once('approval', 1)],
    tags: ['ekonomi', 'konut']
  },
  tariff_hike: {
    id: 'tariff_hike',
    label: 'Gümrük vergisi',
    summary: 'Bir ülkenin mallarına ek vergi. Yerli üretici sevinir, karşı taraf zarar görür; ticaret gerginleşir.',
    hint: 'Raise tariffs on another country’s goods: protects local producers, hurts the target, invites retaliation.',
    category: 'economy',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: [...BILATERAL, { kind: 'max_active', count: 2 }],
    modifiers: [perTurn('economy', -1), once('approval', 1, 'actor'), once('economy', -1, 'actor'), once('reputation', -1, 'actor')],
    tags: ['ekonomi', 'ticaret']
  },
  energy_deal: {
    id: 'energy_deal',
    label: 'Enerji anlaşması',
    summary: 'Uzun vadeli gaz ya da petrol anlaşması: fabrikalar rahatlar. Tedarikçiye bağımlılık artar.',
    hint: 'Long-term energy supply deal with a producer: cheaper energy for both economies, more dependence on the supplier.',
    category: 'economy',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 6,
    unique: true,
    rules: [...BILATERAL, { kind: 'max_active', count: 2 }],
    modifiers: [perTurn('economy', 1, 'actor'), once('sovereignty', -1, 'actor'), perTurn('economy', 1)],
    tags: ['enerji', 'ekonomi']
  },

  // domestic
  security_operation: {
    id: 'security_operation',
    label: 'Güvenlik operasyonu',
    summary: 'Suç örgütlerine ve terör hücrelerine geniş operasyon. Güven hissi artar, hak örgütleri eleştirir.',
    hint: 'Large domestic security sweep: more order and some popularity, human-rights criticism abroad.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 2,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('stability', 3), once('approval', 1), once('reputation', -1)],
    tags: ['ic-siyaset', 'guvenlik']
  },
  judicial_reform: {
    id: 'judicial_reform',
    label: 'Yargı reformu',
    summary: 'Bağımsız yargı adımları dünyada itibar kazandırır. Kurulu düzen rahatsız olur.',
    hint: 'Judicial independence reforms: better image abroad, unsettles the establishment.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('reputation', 3), once('stability', -2), once('approval', 1)],
    tags: ['ic-siyaset', 'yargi']
  },
  cabinet_reshuffle: {
    id: 'cabinet_reshuffle',
    label: 'Kabine değişikliği',
    summary: 'Yıpranan bakanlar gider, yeni yüzler gelir. Tazelik kısa sürer; sık yapılamaz.',
    hint: 'Reshuffle the cabinet: a short-lived fresh start; can only be done now and then.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 6,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('approval', 2), once('stability', 1)],
    tags: ['ic-siyaset', 'kabine']
  },
  emergency_rule: {
    id: 'emergency_rule',
    label: 'Olağanüstü hal',
    summary: 'Sokaklar hemen sakinleşir. Özgürlükler kısılır, halk ve dünya tepki gösterir.',
    hint: 'Declare a state of emergency: immediate order, unpopular, very bad press abroad, daily life suffers.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('stability', 5), once('approval', -3), once('reputation', -5), perTurn('welfare', -1)],
    tags: ['ic-siyaset', 'ohal']
  },
  national_rally: {
    id: 'national_rally',
    label: 'Milli birlik mitingi',
    summary: 'Büyük meydan mitingleriyle halk kenetlenir. Dışarıdan milliyetçi bir hava olarak görülür.',
    hint: 'Mass rallies for national unity: a popularity boost, reads as nationalism abroad.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('approval', 3), once('stability', 1), once('reputation', -1)],
    tags: ['ic-siyaset', 'miting']
  },
  opposition_crackdown: {
    id: 'opposition_crackdown',
    label: 'Muhalefete baskı',
    summary: 'Muhalif liderlere davalar, yasaklar. Kısa vadede kontrol artar; halk ve dünya bunu unutmaz.',
    hint: 'Prosecute and ban opposition figures: more control now, unpopular, a heavy blow to the country’s image.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('stability', 3), once('approval', -2), once('reputation', -5)],
    tags: ['ic-siyaset', 'muhalefet']
  },
  education_reform: {
    id: 'education_reform',
    label: 'Eğitim reformu',
    summary: 'Okullara ve öğretmene yatırım. Meyvesi yavaş gelir; geçiş dönemi sancılıdır.',
    hint: 'Education reform: slow, lasting gains in living standards; costly and disruptive at first.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 6,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('economy', -1), once('approval', -1), perTurn('welfare', 1)],
    tags: ['ic-siyaset', 'egitim']
  },
  migration_control: {
    id: 'migration_control',
    label: 'Göç kontrolü',
    summary: 'Sınırlar sıkılaşır, geri gönderimler başlar. Halk destekler, insan hakları çevreleri eleştirir.',
    hint: 'Tighten borders and migration rules: popular at home, criticised abroad, costs money.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('approval', 2), once('reputation', -2), once('economy', -1)],
    tags: ['ic-siyaset', 'goc']
  },

  // foreign
  state_visit: {
    id: 'state_visit',
    label: 'Resmî ziyaret',
    summary: 'Üst düzey ziyaret: fotoğraflar, anlaşma imzaları, iyi niyet. İki taraf da prestij kazanır.',
    hint: 'A state visit to another country: goodwill and prestige for both sides; opens doors.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 2,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('reputation', 2, 'actor'), once('approval', 1, 'actor'), once('reputation', 1)],
    tags: ['diplomasi', 'ziyaret']
  },
  backchannel_talks: {
    id: 'backchannel_talks',
    label: 'Gizli görüşme',
    summary: 'Kapalı kapılar ardında pazarlık. Hemen hiçbir şey değişmez; ya meyve verir ya sızar.',
    hint: 'Secret talks with another government: nothing visible now; may pay off later or leak.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: BILATERAL,
    modifiers: [],
    tags: ['diplomasi', 'gizli']
  },
  peace_mediation: {
    id: 'peace_mediation',
    label: 'Arabuluculuk',
    summary: 'Bir çatışmada ara bulucu olmak dünyada itibar kazandırır. İçeride "başkasının derdi" diyenler çıkar.',
    hint: 'Mediate in another country’s conflict: prestige if it works, domestic grumbling, risk of failure.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('reputation', 3, 'actor'), once('approval', 1, 'actor'), once('stability', -1, 'actor'), once('stability', 1)],
    tags: ['diplomasi', 'baris']
  },
  recall_ambassador: {
    id: 'recall_ambassador',
    label: 'Büyükelçiyi geri çağır',
    summary: 'Sert bir diplomatik mesaj. İçeride dik duruş olarak görülür, ilişkiler soğur.',
    hint: 'Recall your ambassador from another country: a strong protest, cools relations.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('reputation', -1), once('approval', 1, 'actor'), once('reputation', -1, 'actor')],
    tags: ['diplomasi', 'kriz']
  },
  defense_pact: {
    id: 'defense_pact',
    label: 'Savunma işbirliği',
    summary: 'Ortak tatbikat, istihbarat paylaşımı, silah üretimi. Ordu güçlenir, müttefike bağ artar.',
    hint: 'Defence cooperation agreement with another country: both militaries gain, some independence is traded away.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 6,
    unique: true,
    rules: [...BILATERAL, { kind: 'max_active', count: 2 }],
    modifiers: [once('military', 2, 'actor'), once('sovereignty', -1, 'actor'), once('reputation', 1, 'actor'), once('military', 1)],
    tags: ['diplomasi', 'savunma']
  },
  humanitarian_aid: {
    id: 'humanitarian_aid',
    label: 'İnsani yardım',
    summary: 'Afet ya da savaş bölgesine yardım. Dünyada saygınlık kazandırır; kasadan çıkar.',
    hint: 'Send humanitarian aid to another country: helps its people, earns prestige, costs money.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 1,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('welfare', 2), once('reputation', 2, 'actor'), once('economy', -1, 'actor')],
    tags: ['diplomasi', 'yardim']
  },
  arms_embargo: {
    id: 'arms_embargo',
    label: 'Silah ambargosu',
    summary: 'Bir ülkeye silah ve parça satışı durdurulur. Hedefin ordusu zayıflar; savunma ihracatı kaybedilir.',
    hint: 'Arms embargo on another country: weakens its military over time, costs defence exports.',
    category: 'foreign',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: BILATERAL,
    modifiers: [perTurn('military', -1), once('reputation', 1, 'actor'), once('economy', -1, 'actor')],
    tags: ['diplomasi', 'ambargo']
  },
  summit_hosting: {
    id: 'summit_hosting',
    label: 'Zirveye ev sahipliği',
    summary: 'Dünya liderleri İstanbul’da. İtibar ve gurur kazandırır; organizasyon pahalıdır.',
    hint: 'Host an international summit: prestige and pride, an expensive show.',
    category: 'foreign',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 6,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('reputation', 3), once('approval', 1), once('economy', -1)],
    tags: ['diplomasi', 'zirve']
  },

  // military
  border_deployment: {
    id: 'border_deployment',
    label: 'Sınıra yığınak',
    summary: 'Bir komşunun sınırına asker ve zırhlı araç. İçeride güven, karşıda tedirginlik; masrafı her ay sürer.',
    hint: 'Mass troops on the border with another country: signals strength, unsettles the neighbour, costs money every month.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('military', 1, 'actor'), once('stability', 1, 'actor'), perTurn('economy', -1, 'actor'), once('reputation', -1, 'actor'), once('stability', -2)],
    tags: ['askeri', 'sinir']
  },
  military_exercise: {
    id: 'military_exercise',
    label: 'Tatbikat',
    summary: 'Büyük askerî tatbikat. Ordu hazırlığı artar; komşular bunu mesaj olarak okur.',
    hint: 'Large military exercise: better readiness, read as a message by neighbours.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 3,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('military', 2), once('economy', -1), once('reputation', -1)],
    tags: ['askeri', 'tatbikat']
  },
  cross_border_operation: {
    id: 'cross_border_operation',
    label: 'Sınır ötesi operasyon',
    summary: 'Komşu topraklarda askerî harekât. Halk bayrak etrafında toplanır; ordu yıpranır, ekonomi ve itibar bedel öder. Ancak belirgin askerî üstünlük varsa mümkün.',
    hint: 'A military operation inside another country: rally-round-the-flag at home, heavy costs; only possible with a clear military edge over the target.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 2,
    durationTurns: 3,
    unique: true,
    rules: [...BILATERAL, { kind: 'military_edge', margin: 15 }, { kind: 'max_active', count: 1 }],
    modifiers: [
      once('approval', 3, 'actor'),
      once('military', -2, 'actor'),
      perTurn('economy', -2, 'actor'),
      once('reputation', -4, 'actor'),
      once('stability', -6),
      once('military', -3)
    ],
    tags: ['askeri', 'operasyon']
  },
  arms_purchase: {
    id: 'arms_purchase',
    label: 'Silah alımı',
    summary: 'Bir ülkeden uçak, füze, hava savunması. Ordu hemen güçlenir; pahalıdır ve satıcıya bağımlılık getirir.',
    hint: 'Buy advanced weapons from another country: an instant military boost, expensive, creates dependence on the seller.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 4,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('military', 3, 'actor'), once('economy', -2, 'actor'), once('sovereignty', -1, 'actor'), once('economy', 1)],
    tags: ['askeri', 'silah']
  },
  defense_industry: {
    id: 'defense_industry',
    label: 'Yerli savunma sanayii',
    summary: 'Kendi İHA’nı, tankını, gemini üret. Ordu her ay biraz güçlenir, bağımsızlık artar; başlangıç pahalı.',
    hint: 'Invest in a domestic defence industry: steady military growth and more independence, costly start.',
    category: 'military',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 5,
    unique: true,
    rules: DOMESTIC,
    modifiers: [perTurn('military', 1), once('economy', -2), once('sovereignty', 2)],
    tags: ['askeri', 'savunma-sanayi']
  },
  mobilization: {
    id: 'mobilization',
    label: 'Seferberlik',
    summary: 'Yedekler silah altına. Ordu bir anda büyür; ekonomi her ay ağır bedel öder, halk huzursuzlanır.',
    hint: 'General mobilisation: a big immediate military boost, a heavy monthly economic cost, public unease.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 2,
    durationTurns: 3,
    unique: true,
    rules: DOMESTIC,
    modifiers: [once('military', 5), perTurn('economy', -2), once('approval', -2), once('stability', -1)],
    tags: ['askeri', 'seferberlik']
  },
  naval_show_of_force: {
    id: 'naval_show_of_force',
    label: 'Denizde gövde gösterisi',
    summary: 'Donanma tartışmalı sulara çıkar. İçeride alkış, dışarıda "kışkırtıcı" tepkisi.',
    hint: 'Send the navy into disputed waters near another country: applause at home, tension and bad press abroad.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 2,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('approval', 1, 'actor'), once('reputation', -2, 'actor'), once('stability', -1)],
    tags: ['askeri', 'deniz']
  },
  ceasefire_offer: {
    id: 'ceasefire_offer',
    label: 'Barış teklifi',
    summary: 'Gerginlik yaşanan ülkeye ateşkes ve müzakere önerisi. Dünya takdir eder, içeride şahinler kızar.',
    hint: 'Offer a ceasefire or peace talks to a rival: praised abroad, hawks at home are unhappy.',
    category: 'military',
    target: 'country',
    actors: ['player', 'foreign'],
    cost: 1,
    durationTurns: 2,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('reputation', 2, 'actor'), once('approval', -1, 'actor'), once('stability', 1)],
    tags: ['askeri', 'baris']
  },
  reckless_gambit: {
    id: 'reckless_gambit',
    label: 'Maceracı girişim',
    summary: 'İmkânsız bir hedef için kaynak ve itibar harcandı. Girişim ters teper.',
    hint: 'The government tried something it could not pull off: the failed attempt itself costs popularity, image and stability. Use it when the player’s order was impossible but was actually attempted.',
    category: 'domestic',
    target: 'country',
    actors: ['player'],
    cost: 1,
    durationTurns: 1,
    unique: false,
    card: false,
    rules: DOMESTIC,
    modifiers: [once('approval', -2), once('reputation', -3), once('stability', -1)],
    tags: ['ic-siyaset', 'basarisizlik']
  },

  // what others and the world do
  border_incident: {
    id: 'border_incident',
    label: 'Sınır olayı',
    summary: 'Sınırda çatışma, şehit ya da yaralı haberi.',
    hint: 'A deadly incident on the border: shock and anger, the army takes a hit.',
    category: 'world',
    target: 'country',
    actors: ['world', 'foreign'],
    cost: 0,
    durationTurns: 1,
    unique: false,
    rules: [],
    modifiers: [once('stability', -3), once('approval', -1), once('military', -1)],
    tags: ['askeri', 'sinir']
  },
  cyber_attack: {
    id: 'cyber_attack',
    label: 'Siber saldırı',
    summary: 'Bankalar, enerji şebekesi ya da devlet sistemleri hedef alındı.',
    hint: 'A state-backed cyber attack on the target’s banks, grid or government systems.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 2,
    unique: true,
    rules: BILATERAL,
    modifiers: [perTurn('economy', -1), once('stability', -2)],
    tags: ['siber', 'guvenlik']
  },
  tourism_boycott: {
    id: 'tourism_boycott',
    label: 'Turizm boykotu',
    summary: 'Bir ülke vatandaşlarını seyahat konusunda uyarıyor, turlar iptal ediliyor.',
    hint: 'A country warns its citizens off travelling to the target; tourism income drops.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 4,
    unique: true,
    rules: BILATERAL,
    modifiers: [perTurn('economy', -1)],
    tags: ['turizm', 'ekonomi']
  },
  refugee_wave: {
    id: 'refugee_wave',
    label: 'Göç dalgası',
    summary: 'Komşudaki kriz yüz binleri sınıra getirdi.',
    hint: 'A crisis next door sends a wave of refugees across the border.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 3,
    unique: false,
    rules: [],
    modifiers: [perTurn('welfare', -1), once('stability', -2), once('approval', -2)],
    tags: ['goc', 'kriz']
  },
  security_crisis: {
    id: 'security_crisis',
    label: 'Güvenlik krizi',
    summary: 'Büyük bir güvenlik zafiyeti ülkeyi sarstı.',
    hint: 'A serious security breach or attack shakes the country.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 1,
    unique: false,
    rules: [],
    modifiers: [once('stability', -4), once('approval', -2)],
    tags: ['guvenlik', 'kriz']
  },
  diplomatic_support: {
    id: 'diplomatic_support',
    label: 'Diplomatik destek',
    summary: 'Bir ülke açıkça arkanda durdu.',
    hint: 'Another country publicly backs the target in a dispute.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 1,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('reputation', 2), once('approval', 1)],
    tags: ['diplomasi', 'destek']
  },
  credit_downgrade: {
    id: 'credit_downgrade',
    label: 'Kredi notu indirimi',
    summary: 'Derecelendirme kuruluşları notu düşürdü, borçlanma pahalandı.',
    hint: 'Rating agencies downgrade the country: borrowing gets expensive, investors pull back.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 3,
    unique: false,
    rules: [],
    modifiers: [once('economy', -2), perTurn('economy', -1), once('reputation', -1)],
    tags: ['ekonomi', 'kredi-notu']
  },
  credit_upgrade: {
    id: 'credit_upgrade',
    label: 'Kredi notu artışı',
    summary: 'Not yükseldi, sermaye girişi hızlandı.',
    hint: 'Rating agencies upgrade the country: cheaper credit and inflows.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 3,
    unique: true,
    rules: [],
    modifiers: [perTurn('economy', 1), once('reputation', 1)],
    tags: ['ekonomi', 'kredi-notu']
  },
  energy_discount: {
    id: 'energy_discount',
    label: 'Enerji indirimi',
    summary: 'Tedarikçi ülke gazı ucuzlattı; karşılığında bir beklentisi var.',
    hint: 'A supplier cuts its energy price for the target, expecting favours in return.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 4,
    unique: true,
    rules: BILATERAL,
    modifiers: [perTurn('economy', 1), once('sovereignty', -1)],
    tags: ['enerji', 'ekonomi']
  },
  military_threat: {
    id: 'military_threat',
    label: 'Askerî tehdit',
    summary: 'Bir ülke açık askerî tehditte bulundu.',
    hint: 'Another country openly threatens military action against the target: unease, but also rallying.',
    category: 'foreign',
    target: 'country',
    actors: ['foreign'],
    cost: 0,
    durationTurns: 1,
    unique: true,
    rules: BILATERAL,
    modifiers: [once('stability', -2), once('approval', 1)],
    tags: ['askeri', 'tehdit']
  },
  scandal: {
    id: 'scandal',
    label: 'Skandal',
    summary: 'Sızan belgeler ya da ses kayıtları hükümeti zor durumda bıraktı.',
    hint: 'A leak or scandal embarrasses the government.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 1,
    unique: false,
    rules: [],
    modifiers: [once('approval', -3), once('reputation', -2)],
    tags: ['ic-siyaset', 'skandal']
  },
  strike_wave: {
    id: 'strike_wave',
    label: 'Grev dalgası',
    summary: 'Sendikalar iş bıraktı, üretim durdu.',
    hint: 'Unions strike across the country: production stops, the government looks weak.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 2,
    unique: false,
    rules: [],
    modifiers: [perTurn('economy', -1), once('approval', -1)],
    tags: ['ekonomi', 'grev']
  },
  public_goodwill: {
    id: 'public_goodwill',
    label: 'Halkın takdiri',
    summary: 'Bir karar beklenmedik şekilde halkın gönlünü kazandı.',
    hint: 'A past decision unexpectedly wins public sympathy.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 1,
    unique: false,
    rules: [],
    modifiers: [once('approval', 2), once('stability', 1)],
    tags: ['ic-siyaset']
  },
  export_boom: {
    id: 'export_boom',
    label: 'İhracat patlaması',
    summary: 'Siparişler yağıyor, fabrikalar tam kapasite.',
    hint: 'Export orders surge; factories run at full capacity.',
    category: 'world',
    target: 'country',
    actors: ['world'],
    cost: 0,
    durationTurns: 2,
    unique: true,
    rules: [],
    modifiers: [perTurn('economy', 2)],
    tags: ['ekonomi', 'ihracat']
  }
}

/** Effects the player's government can choose, in catalog order. */
export const PLAYER_EFFECT_IDS = EFFECT_IDS.filter((id) => EFFECTS[id].actors.includes('player'))

/** Player moves offered as ready-made cards: shortcuts, the typed order is the real game. */
export const CARD_EFFECT_IDS = PLAYER_EFFECT_IDS.filter((id) => EFFECTS[id].card !== false)

/** Compact catalog for the LLM's (cached) system prompt: ids and words only, never numbers. */
export function catalogForPrompt(): Array<Pick<EffectDef, 'id' | 'hint' | 'target' | 'actors'>> {
  return EFFECT_IDS.map((id) => {
    const { hint, target, actors } = EFFECTS[id]
    return { id, hint, target, actors }
  })
}
